name: volunteervibe
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  pocketbase: ^0.18.0
  url_launcher: ^6.3.0
  flutter_web_auth_2: ^2.2.0
  flutter_map: ^6.1.0 
  latlong2: ^0.9.0
  flutter_map_location_marker: ^8.0.0 
  google_maps_flutter: ^2.5.0
  geolocator: ^11.0.0 
  flutter_map_marker_cluster: ^1.3.1
  provider: ^6.0.5
  http: ^1.2.1  
  flutter_typeahead: ^5.2.0
  flutter_lints: ^5.0.0
  intl: ^0.18.1
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
      - assets/

